# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rPills_SyleW2U9TcLjnfGBBVyRbbamr
"""

Tangible_fixed_assets = 0
Accumulated_depreciation = 0
Stocks = 0
Debtors = 0
Cash = 0
Capital = 0
Revenue= 0
Expenses = 0
Dividends = 0
Noncurrent_liabilities = 0
Current_liabilities = 0